### ISSUE TITLE
Theme Kit Management commands

### ISSUE THREAD

**Issue by kasemsanm** [29next/theme-kit#5]
As a Prime developer, I want to have theme kit commands so that I can easily manage store theme.

**Exit Criteria**
* we can follow git terminology
   - `ntk list` get list of theme, return theme `id` and `name` to console
   - `ntk init --name THEME NAME` start new project and auto create a config file, create only when init success, if not success should show error message.
   - change current `ntk pull` to `ntk checkout -t {theme_id} -a {apikey} -s {site}` pull all template specific to this theme
   - change `ntk pull` to access an argument
      - `ntk pull arg1 arg2` mean pull only `arg1 and arg2` file
      - `ntk pull` act like `ntk checkout`,  pull all file
   - `ntk push` push theme changes
      - `ntk push arg1 arg2` mean push only `arg1 and arg2` file
      - `ntk push` push all file
   - show preview link in `watch` command as log example `https://sandbox.29next.com/?preview_theme={{theme.id}}`

Example https://shopify.dev/tools/theme-kit/getting-started  

Current NTK theme kit -> https://github.com/29next/theme-kit

**Tasks**  
- [ ] `ntk list` get list of theme, return theme `id` and `name` to console
- [ ] `ntk init --name THEME NAME` start new project and auto create a config file, create only when init success, if not success should show error message.
- [ ] change current `ntk pull` to `ntk checkout -t {theme_id} -a {apikey} -s {site}` pull all template specific to this theme
- [ ] change `ntk pull` to access an argument
  * `ntk pull arg1 arg2` mean pull only `arg1 and arg2` file
  * `ntk pull` act like `ntk checkout`, pull all file
- [ ] `ntk push` push theme changes
  * `ntk push arg1 arg2` mean push only `arg1 and arg2` file
  * `ntk push` push all file
- [ ] show preview link in `watch` command as log example `https://sandbox.29next.com/?preview_theme={{theme.id}}`
